name: bitcoin_cash_dbt
version: 1.0.0
config-version: 2

profile: bitcoin_cash_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  bitcoin_cash_dbt:
    staging:
      +schema: staging
      +materialized: table
    marts:
      +schema: mart
      +materialized: table
